---
    
# - name: Update apt cache
#   apt: update_cache=yes
#   become: yes
  
- name: Install necessities and nice-to-haves
  become: yes
  apt:
    name: ['git', 'htop', 'python-software-properties', 'curl', 'unzip', 'ntp', 'python-pip']
    update_cache: yes
    state: present

- name: install docker-py with pip
  pip:
    name: docker-py
    state: present